BEGIN;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  user_id SERIAL PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  age VARCHAR(30) NOT NULL,
  gender VARCHAR(30) NOT NULL,
  high_school_deploma VARCHAR(30) NOT NULL
);

COMMIT;
